# Dockerfile based on tinibase used by entrecode. By entrecode.
# Version 0.0.1

FROM docker.entrecode.de/tini-build:8.10.0
LABEL maintainer="Simon Scherzinger <scherzinger@entrecode.de>"

EXPOSE 7777
